"""system -> subsystem

Revision ID: 22188377d018
Revises: 852d4a8342bc
Create Date: 2020-07-26 15:48:31.542977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22188377d018'
down_revision = '852d4a8342bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter', sa.Column('id_subsystem', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'parameter', type_='foreignkey')
    op.create_foreign_key(None, 'parameter', 'subsystem', ['id_subsystem'], ['id'])
    op.drop_column('parameter', 'id_system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter', sa.Column('id_system', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'parameter', type_='foreignkey')
    op.create_foreign_key(None, 'parameter', 'subsystem', ['id_system'], ['id'])
    op.drop_column('parameter', 'id_subsystem')
    # ### end Alembic commands ###
